---
abstract: 'add vendor libraries to the module search path'
author:
  - 'Bob Kleemann <bobk@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: lib-vendor
requires:
  Cwd: '0'
  File::Spec: '0'
  FindBin: '0'
  strict: '0'
version: '0.003'
